### PR TITLE
Switched to AsyncKeyedLock

### PR DESCRIPTION
**Pull request by MarkCiliaVincenti**

### CODE REVIEW

**Comment by Aquathing** [comment]
Hello Mark and thank you for your interest in my project. 
May I ask you the reason for this change? Is my implementation broken?

**Comment by MarkCiliaVincenti** [comment]
Hi,

It cleans the code and there's some very small (negligible) performance improvements.

**Comment by Aquathing** [comment]
Thanks for the answer,

I'm not sure adding a dependency to have negligible performance improvements is worth it. 
Right now the bottleneck of that part of the code is actually how the files are downloaded, have you made any measurements to see if it actually improves file downloading?

**Comment by MarkCiliaVincenti** [comment]
I could help with that if you guide me to the part you're referring to.

**Comment by Aquathing** [comment]
Hello Mark, I'd really love to help you but I feel like this is not a genuine contribution but rather an attempt to sponsor your own project.

CatraProto currently does not work, as it requires a newer Telegram API Layer with 64-bit user ids support.
The fact that you've changed an important piece of code, without even testing the changes, makes me think your contribution is not genuine.

I'd be happy to be proved wrong, but I'm going to close this for now.

**Comment by MarkCiliaVincenti** [comment]
Understood. Get it to work and I am happy to help you with synchronisation.

**Comment by Aquathing** [comment]
Thanks, but I still think there is no reason to use your library in my project.

**Pull request closed without merging**
